[APP]
    NAME        = "admin"
    MODE        = "test"
    SECRET      = "Admin Test SECRET"
    SERVER_HOST = ":8080"

[DB]
    HOST        = "172.17.0.2"
    PORT        = "3306"
    USER        = "root"
    PASSWD      = "root@123456"
    DATABASE    = "admin_test"