basePath: /api/v1
definitions:
  types.CommonResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  types.RegisterParam:
    properties:
      account:
        maxLength: 50
        minLength: 4
        type: string
      password:
        maxLength: 18
        minLength: 6
        type: string
    required:
    - account
    - password
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: liyaoo1995@163.com
    name: God Yao
  description: this is Goooooo-Admin Sys.
  version: 1.0.0
paths:
  /create:
    post:
      consumes:
      - application/json
      description: Create Directory
      produces:
      - application/json
      responses: {}
      summary: Create Directory
      tags:
      - Directory
  /db:
    get:
      consumes:
      - application/json
      description: Sys DBStats
      produces:
      - application/json
      responses: {}
      summary: Sys DBStats
      tags:
      - Sys
  /delete:
    put:
      consumes:
      - application/json
      description: Delete Directory
      produces:
      - application/json
      responses: {}
      summary: Delete Directory
      tags:
      - Directory
  /list:
    post:
      consumes:
      - application/json
      description: List Directory
      produces:
      - application/json
      responses: {}
      summary: List Directory
      tags:
      - Directory
  /login:
    post:
      consumes:
      - application/json
      description: User Login
      produces:
      - application/json
      responses: {}
      summary: User Login
      tags:
      - User
  /move:
    put:
      consumes:
      - application/json
      description: Move Directory
      produces:
      - application/json
      responses: {}
      summary: Move Directory
      tags:
      - Directory
  /profile:
    get:
      consumes:
      - application/json
      description: Get UserProfile
      produces:
      - application/json
      responses: {}
      summary: Get UserProfile
      tags:
      - User
  /register:
    post:
      consumes:
      - application/json
      description: User Register
      parameters:
      - description: register
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/types.RegisterParam'
      produces:
      - application/json
      responses:
        "0":
          description: code":0,"data":null,"msg":"Error"}
          schema:
            $ref: '#/definitions/types.CommonResponse'
        "1":
          description: code":1,"data":null,"msg":"Success"}
          schema:
            $ref: '#/definitions/types.CommonResponse'
      summary: User Register
      tags:
      - User
  /rename:
    put:
      consumes:
      - application/json
      description: Rename Directory
      produces:
      - application/json
      responses: {}
      summary: Rename Directory
      tags:
      - Directory
swagger: "2.0"
