[APP]
    NAME        = "JOB"
    MODE        = "dev"
    SECRET      = "JOB Dev SECRET"

[DB]
    HOST        = "localhost"
    PORT        = "3306"
    USER        = "root"
    PASSWD      = "root@123456"
    DATABASE    = "admin_dev"

[LOG]
    DEBUG       = true
    PATH        = "../logs/job.log"
    MAXSIZE     = 1024
    MAXAGE      = 30
    MAXBACKUPS  = 20
    COMPRESS    = false

[REDIS]
    ADDR        = "127.0.0.1:6379"
    PASSWD      = ""
    DB          = 0

[ES]
    ADDR        = "http://127.0.0.1:9200"
    USER        = "elastic"
    PASSWD      = "123456"

[JOB]
    QUEUE       = "machinery_tasks"
    BROKER      = ["127.0.0.1:6379", ]
    BACKEND     = ["127.0.0.1:6379", ]
    BROKERDB    = 0
    BACKENDDB   = 0